### ISSUE TITLE
The drake_cmake_installed example Particle does not plot in visualizer

### ISSUE THREAD

**Issue by huweiATgithub** [RobotLocomotion/drake-external-examples#233] opened 2022-07-24 19:38 UTC
# How to reproduce
- Clone and change directory to [particle example](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_installed/src/particles)
- mkdir build && cd build && cmake .. && make
- Terminal 1: `/opt/drake/bin/drake-visualizer`; Terminal 2: `./uniformly_accelerated_particle`

Then, the texts on the visualizer keep updating (sim time: xxx, real time factor: xxx). But I cannot find the particle. Also, from the Scene Browser of drake-visualizer, I see no scene of the added particle. (neither does the control pane in the meshcat)

# What did I try
- Replace DrakeVisualizer with MeshCatVisualizer.
- Add a simulator->Initialize(); and a sleep after it to look at the visualizer carefully.

# Thoughts
In class ParticleGeometry, the geometry has been added to the scene_graph with the illustration role assigned. Then, I think they will automatically be added to the visualizer attached later?

**Comment by jwnimmer-tri** [comment] 2022-07-26 18:57
Thanks for the report, we'll take a look.

The purpose of `drake-external-examples` is to show how to set up the _build system_ for your projects.  To see examples of Drake's features, a better place to look is drake.mit.edu/#tutorials or https://github.com/RobotLocomotion/drake/tree/master/examples/.

Of course the programs and demo instructions here should still work correctly, but in that light I will probably resolve this bug by deleting the particle code here and replacing it with something simpler.

**Comment by huweiATgithub** [comment] 2022-07-28 19:43
I might have found out the cause of this issue as raised in the drake repo: https://github.com/RobotLocomotion/drake/issues/17649

A current workaround to have things working properly is to drop usage of BuildInto.
I can submit a PR if you think this is ok.

**Comment by jwnimmer-tri** [comment] 2024-09-05 17:42
Thanks for reporting this!

The discussion in https://github.com/RobotLocomotion/drake/issues/17649 is more detailed at this point, so I'm going to close this issue as a duplicate of that other issue.  It's still a bug to be fixed, but it will be easier for the Drake team to track it using the other issue number.

**Closed by jwnimmer-tri** 2024-09-05 17:42 UTC
